export const ADD_FETCHED_DATA = 'ADD_FETCHED_DATA';
export const ADD_FETCHED_DATA_DETAILS = 'ADD_FETCHED_DATA_DETAILS';
export const FILTER_BY_VALUE ='FILTER_BY_VALUE';
export const SORT_POSTS_BY_USER ='SORT_POSTS_BY_USER';
export const UPDATE_POST ='UPDATE_POST';
export const NEW_POST = 'NEW_POST';
export const REMOVE_POST = 'REMOVE_POST';